server:
  port: 8280


# MySQL 和 Redis 连接相关配置
spring:
  application:
    name: ujs_shop_system
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://123.60.188.152:3306/shop?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  redis:
    host: 123.60.188.152
    port: 6379
    database: 0


# Mybatis-Plus相关配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_uuid


image:
  path: C:\wangsj\毕设配图\


